### ISSUE TITLE
Some extra authentication details

### ISSUE THREAD

**Issue by SuperStas** [voryx/Thruway#129]
Hello. 
I'd like to know ip address when a client is authenticate.

Is this true way, adding 
```php
 $arguments->transport_details = $session->getTransport()->getTransportDetails();
```
at here: https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/AuthenticationManager.php#L432

It'll let me know all about transport, including remote address, http headers ( in case using RatchetTransport ) at \Thruway\Authentication\AbstractAuthProviderClient::preProcessAuthenticate method.

I wanted extend AuthenticationManager and overload the method onAuthenticateHandler but it's private.
Thank you.

**Comment by davidwdan** [comment]
@SuperStas Sorry for not responding to this earlier.

If I understand what you're asking, you shouldn't have to change the AuthenticationManager, since all of the transport information is passed to the AuthProvider through the HelloMessage.

You can access the HelloMessage when overriding `AbstractAuthProviderClient::preProcessAuthenticate` in your AuthProvider and then pass it to `processAuthenticate` like this:

```PHP

    public function preProcessAuthenticate(array $args)
    {

        $args      = $args[0];
        $signature = isset($args->signature) ? $args->signature : null;
        $extra     = isset($args->extra) ? $args->extra : null;

        if (!$signature) {
            return ["ERROR"];
        }

        return $this->processAuthenticate($signature, $extra, $args->hello_message);

    }

```

All of the transport information is within the HelloMessage details:  `$helloMessage->getDetails()->transport`

**Comment by SuperStas** [comment]
@davidwdan, thank you.
