### ISSUE TITLE
Denying specific actions

### ISSUE THREAD

**Issue by davidsteinsland** [voryx/Thruway#183]
Perhaps the documentation is a bit lacking, but I don't see a clear way of denying users to publish messages, for example.

Consider an example where clients are only allowed to subscribe to a topic, and the server publishes messages to them (one-way communication). 

What would be the correct way of doing this in Thruway? Adding a listener for some specific event, and then stopping the propagation of it?

**Comment by mbonneau** [comment]
Hi @davidsteinsland ,

I have written a blog post about this here: http://voryx.net/authorization-permissions-with-thruway/

There is also some information about the authorization manager here: https://github.com/voryx/Thruway/wiki/authorization

If you need any other help, feel free to ask here.

**Comment by deli6z** [comment]
We use wamp for real time notifications for our users. Clients subscribe to topics like 'notifications.userID' so that notifications can be published correctly to the qualifying recipient. Now this model won't work b/c everybody can subscribe to any user's notification by just knowing the userID. Roles approach does not really work here b/c role allows only one uri and we have different uri for every user. How should we handle this? Maybe our approach can be improved. Thank you

**Comment by deli6z** [comment]
does thruway support any of this:
http://crossbar.io/docs/Subscriber-Black-and-Whitelisting/

**Comment by davidwdan** [comment]
@deli6z black and whitelisting is supported.  In addition to restricting by sessionid, you can also restrict by authid or role with the publish options: `_thruway_eligible_authids` and `_thruway_eligible_authroles`

**Comment by deli6z** [comment]
Awesome thanks!

**Comment by mbonneau** [comment]
@davidsteinsland - I am going to close this issue. Reopen if you still have questions.
