### ISSUE TITLE
Client Session IP

### ISSUE THREAD

**Issue by WesleyChannon** [voryx/Thruway#220]
Is there a way to retrieve the client session IP (as in the host/IP of the originating, external connection) by using an internal client somehow?

Thanks in advance!

**Comment by mbonneau** [comment]
There are ways to do this - could you specify the use case so that I can give you a more accurate answer? Are you looking to get the address on connection? Are you looking to get the address when an RPC call is made?

**Comment by WesleyChannon** [comment]
I'm looking for the IP address on connection to the router.

**Comment by WesleyChannon** [comment]
Greetings! Just a quick follow up.

@mbonneau: I'm essentially looking for the IP address for an incoming client session that connects directly to the router. In this case, it is a mobile client using autobahn.js through a nginx setup, thats configured to talk to the router directly over localhost.  I've already configured nginx to send things like the REMOTE_HOST and REMOTE_ADDR headers, as well as X-Real-IP and X-Forwarded-* headers.  I just need the router to be able to differentiate between IP addresses, so that I can write some IP-sepcific security within the internal client that is connected to the router already.

**Comment by mbonneau** [comment]
@WesleyChannon - Programmatically, the headers are available on the `RatchetTransport`. If the internal client (which would need to be a realm module) is tracking the sessions by listening to the `PreHelloMessageEvent` event and the `LeaveRealmEvent`, you would be able to inspect this directly on the `Session` by calling `$session->getTransport()->getTransportDetails()['headers']`. (https://github.com/thruway/ratchet-transport/blob/437ceaf2fa6200306a5638a229a41a7d2e9bfebd/src/RatchetTransport.php#L76)

You should check for the existence of the `headers` key first because other transports may not have that (raw and local come to mind).

**Comment by davidwdan** [comment]
Related question:  https://github.com/voryx/Thruway/issues/266
