### ISSUE TITLE
Any chat example please to learn more how it works ?

### ISSUE THREAD

**Issue by miranos** [voryx/Thruway#307]
Hi,

Is there any open source chat example using Autobahn with Thruway ?

Ratchet already have that, want to know if it' the case here too ?

If not, any details on how to procceed ?

Thank's

**Comment by AdamSEY** [comment]
I don't think so, but why do you want to use WAMP? WAMP is a Web Application Messaging protocol and Thruway implemented that protocol.
Take a look on https://github.com/musonza/chat

**Comment by benfavre** [comment]
@AdamSEY What are you on about lol ... He would probably like to use WAMP because that's what it's good for ...

Maybe that laravel lib is relevant, as in it can "maybe" help someone with handling chat data, but it won't help broadcast messages over websockets ..., and that's what this implementation of WAMP is for ...

@miranos No full featured demo that I know of, but I have Thruway running for an app pretty reliably with a RabbitMQ consumer and 0MQ producer.

**Comment by AdamSEY** [comment]
@benfavre Why are you using` RabbitMQ`? it makes your application less scalable and “slower” because the central node adds latency and message envelopes are quite big.

**Comment by benfavre** [comment]
Because it's easy to roll out and I was allready using it.
A client can get a sub 20 ms roundtrip to the backend to run anything I want right now and since it's just an abstraction it is plenty good enough.
Answer : because that's what I used, and I had issues with 0MQ.

**Comment by mbonneau** [comment]
@miranos - I don't believe we have any chat examples. We welcome PRs though if someone would like to make one.
