### ISSUE TITLE
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.

### ISSUE THREAD

**Issue by ccgintranet** [voryx/Thruway#328]
Hello,

The following error is filling up our error logs and it seems to come from Session.php.

Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.

Thanks in advance,

**Comment by immaheshdindigala** [comment]
Hi Team, Any update on above issue. why because even i am facing the same issue, please let me know any alternate solution for this?, Thank you.

**Comment by immaheshdindigala** [comment]
DEPRECATION: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. /var/www/html/magento_MFTF/vendor/symfony/event-dispatcher/EventDispatcher.php:58

**Comment by mbonneau** [comment]
This will be fixed in #343
